// <auto-generated />
namespace Library.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addrelationbetweenlocationsandbook : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addrelationbetweenlocationsandbook));
        
        string IMigrationMetadata.Id
        {
            get { return "202002111516575_add relation between locations and book"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
